#!/bin/bash
COUNT=0
############################################
# CONFIGURATION
WORKSESSIONTIME="25"
PAUSETIME="5"
BIGPAUSE="20"

echo "POMODORI started! - Let's focus!"

while true;do
    while [ $COUNT -le 4 ];do
        echo -en "#############################################################\n"
        echo -en "                           WORK                              \n"
        echo -en "#############################################################\n"
        timer m ${WORKSESSIONTIME}
        kill -9 ${JOBID} 2>/dev/null 1>&2
    
        echo -en "#############################################################\n"
        echo -en "                           PAUSE                             \n"
        echo -en "#############################################################\n"
        timer ${PAUSETIME}
        ((COUNT+1))
        read
    done
    
    echo -en "#############################################################\n"
    echo -en "                      GROSSEPAUSE                            \n"
    echo -en "#############################################################\n"
    timer ${BIGPAUSE}
done
