#!/bin/bash

x=$1

TIME="$(date)"
echo -e "Timer $x Minutes\t(${TIME})"
while [ $x != "0" ]
do
    x=$(( $x - 1 ))
    for (( s=59; s>=0; s-- ))
    do
        echo -en "\t$x : $s \r"
        sleep 1
    done
done    
TIME="$(date)"
echo -e "\n\rTIME OUT\t(${TIME})"
tput bel
